site_name: OpenSemanticLab Python Package (osl)
site_url: https://OpenSemanticLab.github.io/Tools/

plugins:
  - mkdocstrings
      default_handler: python

nav:
    - Home: index.md
    - reference.md

theme: readthedocs
