site_name: OpenSemanticLab Python Package (osl)
site_url: https://OpenSemanticLab.github.io/Tools/

plugins:
- search
plugins:
- mkdocstrings:
    docstring_style: numpy
    handlers:
      python:
        paths: [src]  # search packages in the src folder


nav:
    - Home: index.md
    - reference.md

theme: readthedocs
